### ISSUE TITLE
Crazytimtimtim To-Do

### ISSUE THREAD

**Issue by crazytimtimtim** [Stratosphere-Studios/777-300ER#73]
- [ ] selected magenta alt on PFD
- [ ] Smart knobs for heading and speed
- [ ] GS and LOC indicators not appearing at the correct times (maybe)
- [ ] LOC indicator "zoomed in mode" not enabling at correct time
- [ ] Figure out how to enable XP12's shaking stabilizers
- [ ] Continue work on the FMC and rest of displays

**Comment by crazytimtimtim** [comment]
Next few items in order of priority:
fix existing message logic - complete; untested
fix arrow on right fmc - complete; untested
fix enlarging entries on perf init - in progress
allow > 9 chars to be colored - complete; untested
hdg source sswitch cover - to do
REF NAV DATA - in progress
NAV RAD - in progress
SELECT DESIRED WAYPOINT - to do
RTE1 - to do
ISFD - to do

**Comment by remenkemi** [comment]
need to figure out whether to use cmds or drs for air switches

redo simconfig to be drs only without json?

**Comment by remenkemi** [comment]
check brakes
fix landing gear disappearing

**Comment by remenkemi** [comment]
need to clean up simconfig

- dont reset settings when updating configs. the only solution i can think of currently is to iterate through all old settings and update the new ones. Or i can make a separate list with what was added at each update and just add what's necessary.
- why am i useing newSimConfig? should make a global command to call that doest the same thing and makes everything neater.
- overall messy code I wrote when I was a noob. should clean up

**Comment by remenkemi** [comment]
speaking of dumb stuff the whole fmsdata thing is kinda dumb. maybe i should remove that

**Comment by remenkemi** [comment]
need to do cpdlc and comm manips as well as printer (lol)

**Comment by remenkemi** [comment]
increase "res" of animations, change .1 to like .05

**Comment by remenkemi** [comment]
replace fmc key queue with lambda

**Comment by remenkemi** [comment]
Idea for enhanced setData methods:

Put all fmsdata in some sort of table. setData will take the name of the data as the parameter.
first check will be if the data is null or not. if scratchpad not blank it will continue. if blank and value is null, invalid, otherwise it will copy the value to the scratchpad. 

This may also mean A) placeholders (***** or -----) will need to be done from the page rather than in the data itself, while the data is nul/blank, or B) we can check if values are blank or consist of only  -/*, but this should be standard (i.e. all pages should work the same way.

This will require a decent amount of time but should not be difficult
